### ISSUE TITLE
Several error message with compute_LR_interact Function 

### ISSUE THREAD

**Issue by zyb1984** [kharchenkolab/scITD#19] opened 2023-03-29 08:56 UTC
I  tried to follow the "LR Analysis Tutorial" with the example data, but with several error messages when running "compute_LR_interact "Function, and  the error message information "Error in `class<-`(unlist(lapply(x, as.unit), recursive = FALSE), c("unit",  : NULL cannot have attributes", so I tried to check the code with step by step, and also several warning messages during the process of compute_LR_interact Function,
  With first, may be caused by the "check_rec_pres" function, and with the step "rec_pres <- check_rec_pres(container, lig_ct_exp, rec_elements, target_ct, percentile_exp_rec)", and error information was "Error in intI(i, n = d[1L], dn[[1L]], give.dn = FALSE) : invalid character indexing", and I tried to fix the "check_rec_pres" function with "cells_keep <- rownames(meta)[meta$donors==d ]" to "cells_keep <- rownames(meta[meta$donors==d, ])",  and the fix didn't also work, so I didn't know how to fix this problem, or maybe this is right?
  And the second, with the step of  "fill results matrix with adjusted p-values", and the original code " 
names(myres) <- lig_ct_rec_names
 for (i in 1:length(myres)) {
    lig_ct_rec <- names(myres)[i]
    if (!is.na(myres[[i]])) {
      for (j in 1:length(myres[[i]])) {
        lig_source_target_mod <- names(myres[[i]][j])
        split_nm <- strsplit(lig_source_target_mod, split='_')[[1]]
        mod_nm <- paste0(split_nm[[3]], "_", split_nm[[4]])
        myres_mat[lig_ct_rec, mod_nm] <- myres2[lig_source_target_mod]
      }
    }
  }
",  and in this code, there is an if function but with no else export exit, and how to fix it, or this is right, Also the error message with this step was "Error in if (!is.na(myres[[i]])) { : the condition has length > 1"

**Comment by j-mitchel** [comment] 2023-03-29 13:21
Thanks for trying out scITD! 

I believe this last error is caused by an update in the most recent version of R, which we fixed in our most recent version of scITD on Github (not yet fixed on Cran version). Let me know if you've tried the version of scITD in Github and if the problem persists.

**Comment by zyb1984** [comment] 2023-03-29 13:44
Thank you very much, 
   With the latest version of scITD from Github, all problem had been solved.

**Closed** 2023-03-29 16:03 UTC
